---
title: "Data Visualization"
format: html
---
```{r}
library(readr)
library(dplyr)
library(tidyr)
library(forcats) # makes working with factors easier
library(ggplot2)
library(leaflet) # interactive maps
library(DT) # interactive tables
library(scales) # scale functions for visualization
library(janitor) # expedite cleaning and exploring data
library(viridis) # colorblind friendly color pallet
```
#Read data
```{r}
delta_visits <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=edi.587.1&entityid=cda8c1384af0089b506d51ad8507641f")%>%
janitor::clean_names()
```
##Exploring
```{r}
glimpse(delta_visits)
range(delta_visits$date)
unique(delta_visits$time_of_day)
```

##Getting data ready turning it from wide format to long format
```{r}
visits_long <-delta_visits %>%
  pivot_longer(cols = c("sm_boat", "med_boat", "lrg_boat", "bank_angler", "scientist", "cars"), 
               names_to= "visitor_type",
               values_to= "quantity")%>%
  rename(restore_loc= eco_restore_approximate_location)%>%
  select(-notes)
```

##Plotting with 'ggplot2'
## First make a histogram of visits

```{r}
ggplot(visits_long, 
       aes(x = restore_loc, y= quantity))+
  geom_col()
```

##Calculating daily visits by type and day
```{r}
daily_visit <-visits_long %>%
  group_by(restore_loc, date, visitor_type)%>%
  summarise(daily_visits = sum(quantity))
```

##Customizing our plot
```{r}
ggplot(daily_visit,
       aes(x =  restore_loc, y=daily_visits))+
  geom_col(fill="blue")
```

```{r}
ggplot(daily_visit,
       aes(x = restore_loc, y=daily_visits, 
           fill= visitor_type))+
  geom_col()+
  labs(x= "Restoration Location", 
       y= "Number of Visits",
       fill= "Type of Visitors", 
       title = "Total Number of Visits to Delta Restoration Sites by Visitor Type",
       subtitle= "Sum of all visits during study period")+
  coord_flip()+
  theme_bw()
```

## Using 'theme()" function to further customize our plot

```{r}
ggplot(daily_visit,
       aes(x = restore_loc, y=daily_visits, 
           fill= visitor_type))+
  geom_col()+
  labs(x= "Restoration Location", 
       y= "Number of Visits",
       fill= "Type of Visitors", 
       title = "Total Number of Visits to Delta Restoration Sites by Visitor Type",
       subtitle= "Sum of all visits during study period")+
  coord_flip()+
  theme_bw()+
  theme(legend.position = "bottom",
        axis.ticks.y = element_blank())
```

##Saving theme into an object
```{r}
my_theme <- theme_bw(base_size = 16)+
  theme(legend.position = "bottom", 
                  axis.ticks.y = element_blank())
```

```{r}
ggplot(daily_visit,
       aes(x = restore_loc, y=daily_visits, 
           fill= visitor_type))+
  geom_col()+
  labs(x= "Restoration Location", 
       y= "Number of Visits",
       fill= "Type of Visitors", 
       title = "Total Number of Visits to Delta Restoration Sites by Visitor Type",
       subtitle= "Sum of all visits during study period")+
  coord_flip()+
  my_theme+
  scale_y_continuous(breaks = seq(0, 120, 20))

```


